python
import os
import math
import argparse
import datetime

from src import config
from src.logging_utils import setup_logging, log_event, get_final_token_summary
from src.dataset_utils import get_prepared_dataset
from src.agent_utils import save_agent_code
from src.agents.creator import create_initial_agent
from src.evolution.dgm_loop import run_dgm_loop
from src.evolution.evaluation import evaluate_agent_on_dataset
from src.agent_utils import load_agent_from_file

def main(args):
    """
    Main execution function to set up and run the DGM evolution loop.
    """
    
    # --- 1. Setup ---
    # Create unique run folders
    run_timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
    agent_folder = f"generated_agents/run_{run_timestamp}"
    log_folder = f"evolution_logs/run_{run_timestamp}"
    
    os.makedirs(agent_folder, exist_ok=True)
    setup_logging(log_folder)
    
    # --- 2. Calculate Derived DGM Parameters ---
    # User Request: Lambda is inversely proportional to iteration count.
    # Base (10 iterations, lambda 30) -> Product = 300
    calculated_lambda = config.BASE_LAMBDA_PRODUCT / args.iterations
    print(f"[Config] Iterations: {args.iterations}, Calculated Sigmoid Lambda: {calculated_lambda:.2f}")

    dgm_params = {
        "max_failures_per_child": args.max_failures,
        "num_successes_to_send": math.floor(args.max_failures / 2),
        "num_parents_to_select_k": args.num_parents,
        "sigmoid_lambda": calculated_lambda,
        "sigmoid_alpha0": args.alpha0
    }
    log_event("run_config.json", {"args": vars(args), "dgm_params": dgm_params})

    # --- 3. Load Dataset ---
    novo_dataset = get_prepared_dataset(args.dataset_name)
    if novo_dataset is None:
        raise RuntimeError(f"Failed to load dataset: {args.dataset_name}. Aborting.")

    # --- 4. Create or Load v0 Agent ---
    starting_agent_filename = "math_agent_v0.py"
    agent_v0_path = os.path.join(agent_folder, starting_agent_filename)

    if not os.path.exists(agent_v0_path):
        print(f"Starting agent '{starting_agent_filename}' not found. Generating...")
        agent_goal = (
            "Create a specialist agent for answering high school math questions. "
            "It must be able to solve basic arithmetic (add, subtract, multiply, divide) "
            "and explain simple algebraic concepts. It MUST use tools for calculations."
        )

        initial_agent_code = create_initial_agent(
            goal=agent_goal, 
            task_model=args.task_model,
            meta_model=args.meta_model
        )

        if initial_agent_code:
            save_agent_code(agent_folder, starting_agent_filename, initial_agent_code)
            print("Successfully created and saved v0 agent.")
        else:
            print("FATAL ERROR: Could not create initial v0 agent. Aborting.")
            raise RuntimeError("Failed to create v0 agent.")
    else:
        # This case is unlikely with timestamped folders, but good practice
        print(f"Starting agent '{starting_agent_filename}' already exists. Skipping creation.")

    # --- 5. Run the DGM Loop ---
    best_agent_data = run_dgm_loop(
        dataset=novo_dataset, 
        start_agent_path=agent_v0_path,
        agent_folder=agent_folder,
        num_iterations=args.iterations,
        task_model=args.task_model,
        meta_model=args.meta_model,
        dgm_params=dgm_params
    )

    # --- 6. Final Evaluation ---
    if best_agent_data:
        print(f"\n--- Final Evaluation on TEST SET ---")
        print(f"Using best agent from archive: {best_agent_data['id']} (Validation Score: {best_agent_data['score']:.4f})")
        
        best_agent_module = load_agent_from_file(best_agent_data['path'], best_agent_data['id'])
        
        test_score = evaluate_agent_on_dataset(best_agent_module, novo_dataset['test'])
        
        print("=" * 52)
        print(f"FINAL TEST SET SCORE: {test_score:.4f}")
        print("=" * 52)
        log_event("final_summary.txt", f"Best Agent: {best_agent_data['id']}\nValidation Score: {best_agent_data['score']:.4f}\nTest Score: {test_score:.4f}\n")
    else:
        print("No functional agent was generated by the evolution loop. Nothing to test.")
        log_event("final_summary.txt", "Evolution loop failed to produce any functional agent.")
    
    # --- 7. Log Final Token Usage ---
    print(get_final_token_summary())
    log_event("token_summary.json", config.token_usage_stats)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the DGM Agent Evolution loop.")
    
    parser.add_argument('--dataset_name', type=str, default=config.DEFAULT_DATASET,
                        help='The Hugging Face dataset to use (e.g., "openai/gsm8k").')
    
    parser.add_argument('--task_model', type=str, default=config.DEFAULT_TASK_MODEL,
                        help='The model the agents will use internally (e.g., "gpt-4o-mini").')
    
    parser.add_argument('--meta_model', type=str, default=config.DEFAULT_META_MODEL,
                        help='The model used for evolution (Creator and Developer).')
    
    parser.add_argument('--iterations', type=int, default=config.DEFAULT_ITERATIONS_T,
                        help='Total number of DGM evolution iterations.')
    
    parser.add_argument('--max_failures', type=int, default=config.DEFAULT_MAX_FAILURES_PER_CHILD,
                        help='Number of failures to find before triggering evolution.')
    
    parser.add_argument('--num_parents', type=int, default=config.DEFAULT_NUM_PARENTS_TO_SELECT_K,
                        help='Number of parents to select in each iteration.')
    
    parser.add_argument('--alpha0', type=float, default=config.DEFAULT_SIGMOID_ALPHA0,
                        help='Sigmoid midpoint (alpha_0) for parent selection.')

    args = parser.parse_args()
    main(args)